pipeline {
    agent any

    environment {
        IMAGE_NAME = "subashreedocker/trend-app"
        IMAGE_TAG = "latest"
    }

    stages {

       stage('Clone Repository') {
    steps {
        git branch: 'main', url: 'https://github.com/suba-1994/Trendstore-Application.git'
    }
}
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
            }
        }

        stage('DockerHub Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push $IMAGE_NAME:$IMAGE_TAG'
            }
        }
    }
}
